### PR TITLE
close temp file after upload

### PR DESCRIPTION
**Pull request by luongnhattruong**

### CODE REVIEW

**Review by sakama — COMMENTED** [review]
@luongnhattruong Could you provide more information?
It seems you just added logging and it would not affect to upload/file delete logic.

**Comment by luongnhattruong** [comment]
Hi @sakama ,
"logger.info("Delete generated file: {} > {}", tempFile, tempFile.delete())"  -> tempFile.delete() will return result into log message so we can know if deletion is success or not.

**Review by sakama — COMMENTED** [review]
Ah, understood.
Personally, It does make no sense to include important logic such as `File.delete()` in logging.
There is a possibility other developers overlook important logic.
```java
boolean res = tempFIle.delete()
logger.info("Delete generated file: {} > {}", tempFile, res);
```

**Review by sakama — APPROVED** [review]
LGTM
Thank you for fixing!

**Comment by sakama** [comment]
CI failure is another problem

**Comment by sakama** [comment]
Released as v0.4.4 https://rubygems.org/gems/embulk-output-gcs/versions/0.4.4

**Pull request merged**
